Added code into the getDistanceFromTarget method
Sparx-Robotics-1126/2020-Season pull request #18
Opened 2020-01-25 19:20 UTC by Stephen-the-lad

I did it

2020-01-27 22:32 UTC, ConnoisseurOfCode approved these changes
Looks good. Approved.

2020-01-30 18:46 UTC, secretspy97 commented on src/main/java/frc/sensors/Limelight.java
> +		final double a1 = 15;
It may help if you make these variable names a little most clear on what they represent

2020-02-03 17:30 UTC, secretspy97 requested changes

2020-02-03 17:30 UTC, secretspy97 commented on src/main/java/frc/sensors/Limelight.java
> +		return (h2-h1+15) / Math.tan(Math.toRadians(a1+a2));
Why the random 15?

2020-02-03 17:30 UTC, secretspy97 commented on src/main/java/frc/sensors/Limelight.java
> +	final double a1 = 14.5;
variable name: cameraAngle

2020-02-03 17:30 UTC, secretspy97 commented on src/main/java/frc/sensors/Limelight.java
> +	final double h1 = 59.5;
variable name: robotHeight

2020-02-03 17:30 UTC, secretspy97 commented on src/main/java/frc/sensors/Limelight.java
> +	final double h2 = 98.25; // 83.25  89.5
variable name: targetHeight

2020-02-11 00:25 UTC, merged