done thing that was asked. I thonk.
Sparx-Robotics-1126/2020-Season pull request #2
Opened 2019-11-14 01:18 UTC by kid707

2019-11-21 00:16 UTC, Stephen-the-lad requested changes
Should investigate that the axis value is from the Joystick object. I'm not sure if it's correct as-is.

2019-11-21 14:55 UTC, secretspy97 commented on src/main/java/frc/controllers/Axis.java
> +			return -axis;
The axis parameter represents the axis number of get from the joystick.
Look into joystick.getRawAxis();
https://first.wpi.edu/FRC/roborio/beta/docs/java/edu/wpi/first/wpilibj/GenericHID.html#getRawAxis-int-

2019-12-18 23:48 UTC, Stephen-the-lad approved these changes
Is good

2020-01-17 16:30 UTC, secretspy97 approved these changes

2020-01-17 16:33 UTC, merged