Feature/81 turret tracking
Sparx-Robotics-1126/2020-Season pull request #25
Opened 2020-01-29 23:39 UTC by JTMongeon

Merge

2020-01-29 23:41 UTC, JTMongeon reviewed
test

2020-02-03 17:26 UTC, secretspy97 requested changes
Need to add Tests. See test.frc.drives.commands for test examples

2020-02-03 17:26 UTC, secretspy97 commented on src/main/java/frc/shooter/commands/LimelightTurret.java
> +    double tx;
No need for this to be a class variable

2020-02-03 17:26 UTC, secretspy97 commented on src/main/java/frc/shooter/commands/LimelightTurret.java
> +        if(Math.abs(tx) > deadband) {
With a P-Loop you shouldn't need a deadband. Will have to test

2020-02-11 00:35 UTC, eddy46 approved these changes

2020-02-11 03:34 UTC, merged