Finished getLock method (86)
Sparx-Robotics-1126/2020-Season pull request #27
Opened 2020-02-01 17:05 UTC by stephen318

2020-02-01 17:49 UTC, kid707 approved these changes

2020-02-03 17:05 UTC, secretspy97 requested changes

2020-02-03 17:05 UTC, secretspy97 commented on src/main/java/frc/sensors/Limelight.java
> +		double lock = tv.getDouble(0); //checks if a target is present
Can we use .getBoolean(false) instead of getDouble()?

2020-02-04 14:36 UTC, secretspy97 approved these changes

2020-02-04 14:40 UTC, merged