made shooter command to search for target
Sparx-Robotics-1126/2020-Season pull request #30
Opened 2020-02-04 23:08 UTC by SkF0023

2020-02-04 23:52 UTC, DannyGramowski approved these changes
Works good

Was made by Edward on Danny's computer. My bad

2020-02-05 14:41 UTC, secretspy97 requested changes

2020-02-05 14:41 UTC, secretspy97 commented on src/main/java/frc/shooter/command/ScanForTarget.java
> +    Limelight l;
Unused

2020-02-05 14:41 UTC, secretspy97 commented on src/main/java/frc/shooter/command/ScanForTarget.java
> +        l = new Limelight();
unused

2020-02-05 14:41 UTC, secretspy97 commented on src/main/java/frc/shooter/command/ScanForTarget.java
> +        System.out.println("ScanForTarget.java, logic error");
Unreachable statement - and below

2020-02-05 14:41 UTC, secretspy97 commented on src/main/java/frc/shooter/command/ScanForTarget.java
> +            if(angle<maxAngleOnEitherSide-howCloseToEdge){
This will go to the edge, flip direction and then isolate on the edge, not scanning

2020-02-10 23:20 UTC, closed without merging