scans for the target if it is not detected
Sparx-Robotics-1126/2020-Season pull request #43
Opened 2020-02-10 21:50 UTC by NickRicotta

2020-02-10 23:36 UTC, DannyGramowski approved these changes

2020-02-10 23:46 UTC, eddy46 approved these changes

2020-02-11 18:33 UTC, secretspy97 requested changes

2020-02-11 18:33 UTC, secretspy97 commented on src/main/java/frc/shooter/command/ScannerTarget.java
> +		// TODO Auto-generated method stub
This doesn't do anything!

2020-02-11 23:56 UTC, skyler-ferrante approved these changes

2020-02-12 00:04 UTC, merged